### ISSUE TITLE
Is unittest sample ready to be extracted to it's own repository?

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/appengine-java-snippets#3]
@tmatsuo @lesv

**Comment by tmatsuo** [comment]
Actually I was thinking that we can add more subdirectories, like datastore, search, etc, instead of making this repo an independent one.
What is the rationale of dividing the repositories?

**Comment by elibixby** [comment]
I think it's better from the perspective of "repository status" with CI, and also maybe less confusing. For other projects that are interacting with services I think it makes sense to have shared resources (e.g. the bigquery-samples repo), but for deployable app samples I think it makes more sense to split them.

**Comment by tmatsuo** [comment]
It's really a tiny set of snippets, actually it's not deployable in a real sense because there are only unittests. Do you still want to make it separate?

**Comment by elibixby** [comment]
Maybe we could make this the "services" repo, and have the unittests on the relevant services. This makes more sense to me. Probably could get the TWs onboard for a Doc restructuring if we did this as well.

**Comment by tmatsuo** [comment]
What the full repo name do you suggest? "appengine-services-java" ?
What is the problem with "appengine-java-snippets" which contains docs snippets?

The latter seems more intuitive to me, but I may miss something.

**Comment by elibixby** [comment]
This name is fine. I'm going to work on extracting memcache sample and we can try out integrating unittesting samples with that.
